# Generated by Django 5.2.1 on 2025-05-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_materialorder_note_materialorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialorder',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
