# Generated by Django 5.2.1 on 2025-05-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_materialorder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialorder',
            name='total_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
