# Generated by Django 5.2.2 on 2025-06-10 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_materialorder_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อรอบจัดส่ง')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'รอบจัดส่ง',
                'verbose_name_plural': 'รอบจัดส่ง',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='materialorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'รายการสั่งซื้อ', 'verbose_name_plural': 'รายการสั่งซื้อ'},
        ),
        migrations.AddField(
            model_name='materialorder',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'รออนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ไม่อนุมัติ')], default='pending', max_length=20, verbose_name='สถานะอนุมัติ'),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่อนุมัติ'),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL, verbose_name='ผู้อนุมัติ'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่สั่ง'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='note',
            field=models.TextField(blank=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สั่ง'),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='delivery_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.deliveryround', verbose_name='รอบจัดส่ง'),
        ),
    ]
