# Generated by Django 5.2.1 on 2025-06-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_deliveryround_alter_materialorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialorder',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'รออนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ไม่อนุมัติ')], default='approved', max_length=20, verbose_name='สถานะอนุมัติ'),
        ),
    ]
